import type { CampusTask, KnowledgeSource } from "./types";

export const knowledgeSources: KnowledgeSource[] = [
  {
    id: "policy-course-adjustment",
    title: "调课与停课管理流程",
    department: "教务处",
    version: "2026 春季版",
    effectiveDate: "2026-03-01",
    sourceType: "policy",
    sensitivity: "internal",
    audience: ["teaching-admin", "teacher"],
    summary: "说明调课申请、材料要求、审批节点与通知责任。",
    excerpts: [
      {
        id: "course-adjustment-required-fields",
        sourceId: "policy-course-adjustment",
        heading: "申请材料",
        text: "任课教师申请调课时，应说明课程名称、原上课时间、拟调整时间、调课原因、涉及班级和补课安排。教学秘书应核对冲突后提交教学负责人审核。",
        keywords: ["调课", "申请", "课程", "补课", "审核", "教学秘书"],
      },
      {
        id: "course-adjustment-notice",
        sourceId: "policy-course-adjustment",
        heading: "通知责任",
        text: "调课获批后，教学办应在课程群或学院通知渠道发布调整说明。涉及多个班级的，应同步提醒任课教师确认学生已知晓。",
        keywords: ["调课", "通知", "课程群", "教学办", "学生"],
      },
    ],
  },
  {
    id: "notice-exam-arrangement",
    title: "期末考试组织工作提示",
    department: "教学运行办公室",
    version: "2026 第 2 号",
    effectiveDate: "2026-05-10",
    sourceType: "notice",
    sensitivity: "internal",
    audience: ["teaching-admin", "teacher"],
    summary: "期末考试材料、监考安排、试卷提交和异常上报要求。",
    excerpts: [
      {
        id: "exam-material-deadline",
        sourceId: "notice-exam-arrangement",
        heading: "试卷材料",
        text: "课程负责人应在考试前七个工作日提交试卷、参考答案、评分标准和命题审核表。教学办负责汇总并检查材料完整性。",
        keywords: ["考试", "试卷", "评分标准", "命题", "教学办", "七个工作日"],
      },
      {
        id: "exam-incident-report",
        sourceId: "notice-exam-arrangement",
        heading: "异常处理",
        text: "考试过程中出现缺考、违纪、试卷差错或监考冲突时，监考教师应记录事实并及时报教学办。系统不得自动认定违纪性质。",
        keywords: ["考试", "异常", "违纪", "缺考", "监考", "教学办"],
      },
    ],
  },
  {
    id: "guide-teaching-inspection",
    title: "课堂教学检查材料清单",
    department: "质量监控办公室",
    version: "2026 试行",
    effectiveDate: "2026-04-15",
    sourceType: "guide",
    sensitivity: "internal",
    audience: ["teaching-admin"],
    summary: "课堂检查、听课记录、整改反馈和汇总报告材料要求。",
    excerpts: [
      {
        id: "inspection-materials",
        sourceId: "guide-teaching-inspection",
        heading: "材料清单",
        text: "教学检查材料通常包括听课记录、课程大纲、授课计划、学生反馈摘要、问题清单和整改跟踪表。汇总报告应区分事实、分析和建议。",
        keywords: ["教学检查", "听课", "课程大纲", "整改", "汇总报告"],
      },
      {
        id: "inspection-risk-language",
        sourceId: "guide-teaching-inspection",
        heading: "表述边界",
        text: "检查材料不得直接给出人事处理、处分或教学事故认定结论。涉及高风险判断时，应提交学院或学校相关程序处理。",
        keywords: ["教学检查", "人事", "处分", "教学事故", "高风险"],
      },
    ],
  },
  {
    id: "template-weekly-teaching-plan",
    title: "教师周教学计划模板",
    department: "教研室",
    version: "2026 模板",
    effectiveDate: "2026-02-20",
    sourceType: "template",
    sensitivity: "internal",
    audience: ["teacher"],
    summary: "教师按周整理教学目标、课堂活动、作业和反馈安排的模板。",
    excerpts: [
      {
        id: "weekly-plan-structure",
        sourceId: "template-weekly-teaching-plan",
        heading: "结构",
        text: "周教学计划建议包含本周目标、课前准备、课堂活动、课后作业、评价方式和需要学生提前阅读的材料。",
        keywords: ["周教学计划", "教学目标", "课堂活动", "作业", "评价"],
      },
      {
        id: "assignment-rubric",
        sourceId: "template-weekly-teaching-plan",
        heading: "作业评价",
        text: "作业说明应包含提交形式、评分维度、优秀样例特征和常见问题提醒。评分量规应避免只给笼统分值。",
        keywords: ["作业", "评分", "量规", "提交", "评价"],
      },
    ],
  },
  {
    id: "meeting-teaching-office-weekly",
    title: "教学办周例会纪要样例",
    department: "教学办",
    version: "2026 样例",
    effectiveDate: "2026-05-01",
    sourceType: "meeting",
    sensitivity: "internal",
    audience: ["teaching-admin"],
    summary: "用于生成会议纪要、任务分解和风险提示的样例结构。",
    excerpts: [
      {
        id: "meeting-minutes-structure",
        sourceId: "meeting-teaching-office-weekly",
        heading: "纪要结构",
        text: "会议纪要应包含会议时间、参会人员、议题、形成的决定、待办事项、责任人、截止时间和需要上报的问题。",
        keywords: ["会议纪要", "待办", "责任人", "截止时间", "上报"],
      },
      {
        id: "meeting-task-followup",
        sourceId: "meeting-teaching-office-weekly",
        heading: "跟踪要求",
        text: "待办事项应进入任务台账，按未开始、草稿、审核中、已确认、已完成等状态跟踪。重要事项应保留来源和决策依据。",
        keywords: ["任务台账", "审核", "确认", "来源", "决策依据"],
      },
    ],
  },
];

export const initialTasks: CampusTask[] = [
  {
    id: "task-weekly-inspection",
    title: "整理本周课堂教学检查材料",
    role: "teaching-admin",
    status: "reviewing",
    sourceIds: ["guide-teaching-inspection"],
    dueAt: "2026-06-01",
    createdFrom: "manual",
    detail: "汇总听课记录、问题清单和整改跟踪表，区分事实、分析和建议。",
  },
  {
    id: "task-exam-materials",
    title: "提醒课程负责人提交期末考试材料",
    role: "teaching-admin",
    status: "draft",
    sourceIds: ["notice-exam-arrangement"],
    dueAt: "2026-05-29",
    createdFrom: "qa",
    detail: "检查试卷、参考答案、评分标准和命题审核表是否齐全。",
  },
  {
    id: "task-weekly-plan",
    title: "完善下周课程教学计划",
    role: "teacher",
    status: "draft",
    sourceIds: ["template-weekly-teaching-plan"],
    dueAt: "2026-05-30",
    createdFrom: "manual",
    detail: "补充课前阅读、课堂活动、作业说明和评分量规。",
  },
];
